from __future__ import annotations

from .types import MediaType, MessageType

__all__ = ("DEPRECATED_EVENTS",)


DEPRECATED_EVENTS: dict[str, MediaType | MessageType] = {
    "on_avatar_chat_end": MessageType.AVATAR_CALL_END,
    "on_avatar_chat_not_answered": MessageType.AVATAR_CALL_NO_ANSWERED,
    "on_avatar_chat_cancelled": MessageType.AVATAR_CALL_CANCELLED,
    "on_avatar_chat_declined": MessageType.AVATAR_CALL_DECLINED,
    "on_avatar_chat_start": MessageType.AVATAR_CALL_START,
    "on_chat_background_changed": MessageType.BACKGROUND_CHANGE,
    "on_chat_content_changed": MessageType.BACKGROUND_CHANGE,
    "on_chat_host_transfered": MessageType.HOST_TRANSFERRED,
    "on_chat_icon_changed": MessageType.ICON_CHANGE,
    "on_chat_invite": MessageType.CHAT_CREATED,
    "on_chat_pin_announcement": MessageType.PIN_ANNOUNCEMENT,
    "on_chat_removed_message": MessageType.CHAT_REMOVED,
    "on_chat_tip": MessageType.TIPPING,
    "on_chat_tipping_disabled": MessageType.DISABLE_TIP_PERMISSION,
    "on_chat_tipping_enabled": MessageType.ENABLE_TIP_PERMISSION,
    "on_chat_title_changed": MessageType.TITLE_CHANGE,
    "on_chat_unpin_announcement": MessageType.UNPIN_ANNOUNCEMENT,
    "on_chat_view_only_disabled": MessageType.DISABLE_VIEW_ONLY,
    "on_chat_view_only_enabled": MessageType.ENABLE_VIEW_ONLY,
    "on_delete_message": MessageType.DELETED,
    "on_group_member_join": MessageType.MEMBER_JOIN,
    "on_group_member_leave": MessageType.MEMBER_LEFT,
    "on_image_message": MediaType.IMAGE,
    "on_invite_message": MessageType.INVITE_MESSAGE,
    "on_screen_room_end": MessageType.SCREENING_ROOM_END,
    "on_screen_room_start": MessageType.SCREENING_ROOM_START,
    "on_sticker_message": MessageType.STICKER,
    "on_strike_message": MessageType.STRIKE,
    "on_text_message": MessageType.TEXT,
    "on_text_message_force_removed": MessageType.FORCED_DELETED,
    "on_text_message_removed_by_admin": MessageType.DELETED_BY_MOD,
    "on_timestamp_message": MessageType.TIMESTAMP,
    "on_video_chat_end": MessageType.VIDEO_CALL_END,
    "on_video_chat_not_answered": MessageType.VIDEO_CALL_NO_ANSWERED,
    "on_video_chat_cancelled": MessageType.VIDEO_CALL_CANCELLED,
    "on_video_chat_declined": MessageType.VIDEO_CALL_DECLINED,
    "on_video_chat_start": MessageType.VIDEO_CALL_START,
    "on_voice_chat_end": MessageType.VOICE_CALL_END,
    "on_voice_chat_not_answered": MessageType.VOICE_CALL_NO_ANSWERED,
    "on_voice_chat_cancelled": MessageType.VOICE_CALL_CANCELLED,
    "on_voice_chat_declined": MessageType.VOICE_CALL_DECLINED,
    "on_voice_chat_permission_invite_only": MessageType.VOICE_PERMISSION_INVITE_ONLY,
    "on_voice_chat_permission_invited_and_requested": MessageType.VOICE_PERMISSION_APPROVAL_REQUIRED,
    "on_voice_chat_permission_open_to_everyone": MessageType.VOICE_PERMISSION_OPEN_TO_EVERYONE,
    "on_voice_chat_start": MessageType.VOICE_CALL_START,
    "on_voice_message": MessageType.VOICE,
    "on_welcome_message": MessageType.WELCOME_MESSAGE,
    "on_youtube_message": MediaType.YOUTUBE,
}
